dist: xenial
language: generic
before_install:
  - sudo apt-get install -y libsystemd-dev bash-completion bison debhelper default-jdk flex javahelper libmysql++-dev libsqlite3-dev libssl-dev libws-commons-util-java libxml2-dev libxmlrpc3-client-java libxmlrpc3-common-java libxslt1-dev libcurl4-openssl-dev ruby scons libxmlrpc-c++8-dev npm
  - gem install rubocop
  - sudo npm install -g bower
  - sudo npm install -g grunt
  - sudo npm install -g grunt-cli
  - (cd src/sunstone/public && npm install && bower install)
script:
  - rubocop -c share/linters/.rubocop.yml src/cli
  - set -o errexit; source .travis/smoke_tests.sh
